#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: 📡 Mediatek_Uboot

on:
  workflow_dispatch:
  # schedule:
    # - cron: 0 17 * * *
  # watch:
  #   types: started

env:
  REPO_URL: https://github.com/1715173329/bl-mt798x-oss
  REPO_BRANCH: atf-2025
  FIRMWARE_TAG: Mediatek_Uboot
